version: "3.7"
secrets:
  aws_creds:
    file: $HOME/.aws/credentials

services:
  app:
    platform: linux/amd64
    build: .
    image: ${ECR_REGISTRY}/rb-rebase-beacon:prod
    command: sh -c "npm install --only=prod && npm start"
    working_dir: /app
    ports:
      - 80:80
    environment:
      PORT: 80
      NODE_ENV: production
      SQS_QUEUE_URL: https://sqs.us-west-2.amazonaws.com/016619982582/rebase_beacon_queue
    secrets:
    - source: aws_creds
      target: /root/.aws/credentials
      uid: '1000'
      gid: '1000'
      mode: 0700
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1Gb