version: "3.7"
services:
  app:
    platform: linux/amd64
    build: .
    image: rb-rebase-beacon:local
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      NODE_ENV: local
    volumes:
      - .:/app
